
```{r, results='asis',message=FALSE, warning=FALSE, comment=FALSE,echo=FALSE}
if(!is.null(REPORTING_ENTITY)) cat("# Entity

* Name (English): ", CPC_data[CPC_data$CODE == REPORTING_ENTITY,]$NAME_EN,"
* Name (Français): ", CPC_data[CPC_data$CODE == REPORTING_ENTITY,]$NAME_FR,"
* Status: ", as.character(CPC_data[CPC_data$CODE == REPORTING_ENTITY,]$STATUS),"
* Is SIDS? ",if(CPC_data[CPC_data$CODE == REPORTING_ENTITY,]$IS_SIDS) "**Yes**" else "**No**","
* Is coastal? ",if(CPC_data[CPC_data$CODE == REPORTING_ENTITY,]$IS_COASTAL) "**Yes**" else "**No**","

")
```

# General scenario configuration

||| 
| :-------------------------------------------------- | ------: |
| Species | `r SPECIES_SELECTED` |
| Total allowable catch | `r prettyNum(TARGET_TAC_T, big.mark = ",")` t | 
|  **Main allocation components** ||
| 1 - Baseline weight          | `r BASELINE_WEIGHT*100`% |
| 2 - Developing state weight | `r DEVELOPING_STATE_WEIGHT*100`% |
| 3 - Catch-based weight   | `r CATCH_BASED_WEIGHT*100`% | 
| **Developing State components (item 2)** |||
| 2.1 - Equal share weight    | `r DS_EQUAL_WEIGHT*100`% |
| 2.2 - Least-developed country weight |  `r DS_LDC_WEIGHT*100`% |
| 2.3 - SIDS weight | `r DS_SIDS_WEIGHT*100`% |
| **Catch-based configuration parameters** ||
| Reference years | `r paste(HISTORICAL_CATCH_INTERVAL_START, HISTORICAL_CATCH_INTERVAL_END, sep = "-")` |
| Reference method | `r HISTORICAL_CATCH_METHOD` |
| Part of foreign catch taken in NJA re-attributed to coastal states (Year 1) | `r CATCH_BASED_WEIGHT_NJA_ATTRIBUTION_YEAR_01*100`% |
| Part of foreign catch taken in NJA re-attributed to coastal states (Year 2) | `r CATCH_BASED_WEIGHT_NJA_ATTRIBUTION_YEAR_02*100`% |
| Part of foreign catch taken in NJA re-attributed to coastal states (Year 3) | `r CATCH_BASED_WEIGHT_NJA_ATTRIBUTION_YEAR_03*100`% |
| Part of foreign catch taken in NJA re-attributed to coastal states (Year 4) | `r CATCH_BASED_WEIGHT_NJA_ATTRIBUTION_YEAR_04*100`% |
| Part of foreign catch taken in NJA re-attributed to coastal states (Year 5) | `r CATCH_BASED_WEIGHT_NJA_ATTRIBUTION_YEAR_05*100`% |
| Part of foreign catch taken in NJA re-attributed to coastal states (Year 6) | `r CATCH_BASED_WEIGHT_NJA_ATTRIBUTION_YEAR_06*100`% |
| Part of foreign catch taken in NJA re-attributed to coastal states (Year 7) | `r CATCH_BASED_WEIGHT_NJA_ATTRIBUTION_YEAR_07*100`% |
| Part of foreign catch taken in NJA re-attributed to coastal states (Year 8) | `r CATCH_BASED_WEIGHT_NJA_ATTRIBUTION_YEAR_08*100`% |
| Part of foreign catch taken in NJA re-attributed to coastal states (Year 9) | `r CATCH_BASED_WEIGHT_NJA_ATTRIBUTION_YEAR_09*100`% |
| Part of foreign catch taken in NJA re-attributed to coastal states (Year 10) | `r CATCH_BASED_WEIGHT_NJA_ATTRIBUTION_YEAR_10*100`% |

\newpage