# Configuration {#configuration}

## CPC Status and Characteristics

The definitions of all parameters characterising each CPC in relation to the allocation criteria are provided in the [`cfg/CPC_CONFIGURATIONS.xlsx`](./CPC_CONFIGURATIONS.xlsx) file. This file contains two worksheets:
  
- The **CPC** worksheet lists all current IOTC Contracting Parties (CPs), Liberia as a Cooperating Non-Contracting Party (CNCP), and Taiwan, China as a Fishing Entity (FE). It includes information on CPC status, classification as a Coastal State or Small Island Developing State (SIDS), and the presence and size of National Jurisdiction Areas (NJAs) within the IOTC Area of Competence

- The **COASTAL_STATE_SOCIO_ECONOMIC** worksheet includes all CPCs identified as Coastal States, along with their development status and a set of socio-economic indicators aligned with the requirements of Option 1 and Option 2 under paragraph 6.6(1)(b) of [IOTC-2024-TCAC13-REF02](https://iotc.org/documents/TCAC/13/REF02E).These indicators are used to simulate allocation scenarios that incorporate development and vulnerability criteria.

Detailed descriptions of the fields included in these two worksheets are provided in Appendix A and Appendix B, respectively.

## Historical Catches {#historicalCatch}

Historical catch data are available for albacore, bigeye tuna, skipjack tuna, swordfish, and yellowfin tuna from 1950 to 2021, stratified by year, fleet, gear, school type, species, and assigned area (National Jurisdiction Area or high seas) to support allocation analyses.

To support the application of certain allocation criteria, the IOTC Secretariat estimated historical catches by categorising them according to the area of operation—specifically, whether they occurred on the high seas or within the National Jurisdiction Area (NJA) of a coastal State. For longline and surface fisheries operating on the high seas, this was done by applying the proportion of overlap between each regular grid cell and the corresponding NJA, thereby allocating a share of the catch from each grid cell to the relevant NJA.

The estimation method was presented to the Technical Committee on Allocation Criteria at its twelfth meeting in October 2023 and was endorsed by participants ([IOTC-2023-TCAC12-INF02](https://iotc.org/documents/TCAC/12/INF02)).

The NJAs of the IOTC CPCs were sourced from the Flanders Marine Institute [*maritime boundaries* geodatabase](https://doi.org/10.14284/628). They are available for download from the [IOTC Data Reference Catalogue](https://data.iotc.org/reference/latest/domain/admin/shapefiles/IO_NJA_AREAS_1.0.0_SHP.zip).




