---
title: "Simulation Tool for Allocation Criteria: Data, Assumptions, and Output"
author: "Author: [IOTC Secretariat](mailto:IOTC-Secretariat@fao.org)" 
output:
  officedown::rdocx_document:
    reference_docx: "./templates/rdoc_template.docx"
reference_num: TRUE
fig_caption: TRUE
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      tab.cap.pre = "Tab. ", 
                      tab.cap.sep = ". ", 
                      tab.cap.style = "Table Caption", 
                      tab.cap.fp_text = officer::fp_text_lite(italic = FALSE, bold = TRUE), 
                      fig.cap = TRUE, 
                      fig.cap.pre = "Fig. ", 
                      fig.cap.sep = ". ", 
                      fig.cap.style = "Caption label",
                      dpi = 300
)
```

```{r Headers, echo = FALSE}
logo.file = file.path("./templates/FAO_IOTC_LOGOS.png")

bl_header_no_logo = function(txt, position) {
  block_list(
    fpar(values = txt, fp_p = fp_par(text.align = position, border.bottom = fp_border()), fp_t = fp_text_lite(color = "black", bold = FALSE, font.size = 12))
  )
}

bl_header_with_logo = function(txt, position) {
  block_list(
    fpar(external_img(src = logo.file, height = 0.71, width = 7.19, unit = "in"), 
    ftext = txt, 
         fp_p = fp_par(text.align = position, border.bottom = fp_border()), 
         fp_t = fp_text_lite(color = "black", bold = FALSE, font.size = 12)))
}

sec_pr = prop_section(
  header_first = bl_header_with_logo("IOTC-2025-TCAC15-INF02", "right"),
  header_default = bl_header_no_logo("IOTC-2025-TCAC15-INF02", "right")
)

```

```{r TextStyles, echo = FALSE, eval = TRUE}
fp = fp_par(
  text.align = "center", 
  padding.bottom = 20, padding.top = 120, 
  border.bottom = fp_border())

alert = fp_text(shading.color = "transparent", bold = TRUE, color = "red")
underline = fp_text(underlined = TRUE)
```

```{r eval = TRUE}
block_section(sec_pr)
```

```{r child = "06_01_Purpose.Rmd"}
```

```{r child = "06_02_Inputs.Rmd"}
```

```{r child = "06_03_Simulations.Rmd"}
```

```{r child = "06_04_Results.Rmd"}
```

\pagebreak

```{r child = "06_Appendix_01_CPC_Data.Rmd", eval = FALSE}
```



```{r child = "06_Appendix_02_Coastal_State_Data.Rmd"}
```

\pagebreak

```{r child = "06_Appendix_03_Catch_Data", eval = FALSE}
```

```{r, echo = F}
block_section(sec_pr)
```