# Source the scripts for loading and plotting the data
setwd("./initialisation/")
source("./00_CORE.R")
setwd("..")

# CONFIGURE MULTIPLE SCENARIOS ####
SCENARIO_PARAMETERS = fread("./inputs/IOTC-2024-TCAC13-REF03_Rev1_-_INPUT_PARAMETERS.csv")

for (i in 1:nrow(SCENARIO_PARAMETERS)){
  
BASELINE_WEIGHT      = SCENARIO_PARAMETERS$BASELINE_WEIGHT[i] 
COASTAL_STATE_WEIGHT = SCENARIO_PARAMETERS$COASTAL_STATE_WEIGHT[i]
CATCH_BASED_WEIGHT   = 1 - (BASELINE_WEIGHT + COASTAL_STATE_WEIGHT)

# COASTAL STATE COMPONENT (species-independent)
CS_EQUAL_WEIGHT          = SCENARIO_PARAMETERS$CS_EQUAL_WEIGHT[i]
CS_SOCIO_ECONOMIC_WEIGHT = SCENARIO_PARAMETERS$CS_SOCIO_ECONOMIC_WEIGHT[i]
SE_HDI_WEIGHT = SCENARIO_PARAMETERS$SE_HDI_WEIGHT[i]
SE_GNI_WEIGHT = SCENARIO_PARAMETERS$SE_GNI_WEIGHT[i]
SE_SID_WEIGHT = SCENARIO_PARAMETERS$SE_SID_WEIGHT[i]
CS_NJA_WEIGHT = 1 - (CS_EQUAL_WEIGHT + CS_SOCIO_ECONOMIC_WEIGHT) 

# CATCH-BASED COMPONENT
SPECIES_CODE_SELECTED           = SCENARIO_PARAMETERS$SPECIES_CODE_SELECTED[i]
SPECIES_SELECTED                = SPECIES_TABLE[SPECIES_CODE == SPECIES_CODE_SELECTED, SPECIES]
TARGET_TAC_T                    = SCENARIO_PARAMETERS$TARGET_TAC_T[i]
HISTORICAL_CATCH_INTERVAL_START = SCENARIO_PARAMETERS$HISTORICAL_CATCH_INTERVAL_START[i]
HISTORICAL_CATCH_INTERVAL_END   = SCENARIO_PARAMETERS$HISTORICAL_CATCH_INTERVAL_END[i]
HISTORICAL_CATCH_AVERAGE        = get(SCENARIO_PARAMETERS$HISTORICAL_CATCH_AVERAGE[i])    # or best_years_average_catch_data
HISTORICAL_CATCH_METHOD         = ifelse(sum(nchar(deparse(HISTORICAL_CATCH_AVERAGE)))>200, "Best \"n\" years", "Selected period")
CATCH_BASED_WEIGHT_NJA_ATTRIBUTION_YEAR_01 = SCENARIO_PARAMETERS$ALLOCATION_TRANSITION_Y1[i]
CATCH_BASED_WEIGHT_NJA_ATTRIBUTION_YEAR_02 = SCENARIO_PARAMETERS$ALLOCATION_TRANSITION_Y2[i]
CATCH_BASED_WEIGHT_NJA_ATTRIBUTION_YEAR_03 = SCENARIO_PARAMETERS$ALLOCATION_TRANSITION_Y3[i]
CATCH_BASED_WEIGHT_NJA_ATTRIBUTION_YEAR_04 = SCENARIO_PARAMETERS$ALLOCATION_TRANSITION_Y4[i]
CATCH_BASED_WEIGHT_NJA_ATTRIBUTION_YEAR_05 = SCENARIO_PARAMETERS$ALLOCATION_TRANSITION_Y5[i]
CATCH_BASED_WEIGHT_NJA_ATTRIBUTION_YEAR_06 = SCENARIO_PARAMETERS$ALLOCATION_TRANSITION_Y6[i]
CATCH_BASED_WEIGHT_NJA_ATTRIBUTION_YEAR_07 = SCENARIO_PARAMETERS$ALLOCATION_TRANSITION_Y7[i]
CATCH_BASED_WEIGHT_NJA_ATTRIBUTION_YEAR_08 = SCENARIO_PARAMETERS$ALLOCATION_TRANSITION_Y8[i]
CATCH_BASED_WEIGHT_NJA_ATTRIBUTION_YEAR_09 = SCENARIO_PARAMETERS$ALLOCATION_TRANSITION_Y9[i]
CATCH_BASED_WEIGHT_NJA_ATTRIBUTION_YEAR_10 = SCENARIO_PARAMETERS$ALLOCATION_TRANSITION_Y10[i]
ALLOCATION_TRANSITION = c(CATCH_BASED_WEIGHT_NJA_ATTRIBUTION_YEAR_01, CATCH_BASED_WEIGHT_NJA_ATTRIBUTION_YEAR_02, CATCH_BASED_WEIGHT_NJA_ATTRIBUTION_YEAR_03, CATCH_BASED_WEIGHT_NJA_ATTRIBUTION_YEAR_04, CATCH_BASED_WEIGHT_NJA_ATTRIBUTION_YEAR_05, CATCH_BASED_WEIGHT_NJA_ATTRIBUTION_YEAR_06, CATCH_BASED_WEIGHT_NJA_ATTRIBUTION_YEAR_07, CATCH_BASED_WEIGHT_NJA_ATTRIBUTION_YEAR_08, CATCH_BASED_WEIGHT_NJA_ATTRIBUTION_YEAR_09, CATCH_BASED_WEIGHT_NJA_ATTRIBUTION_YEAR_10)

# Source the R allocation scripts
setwd("./initialisation/")
source("./05_SCENARIO_ALLOCATION_COMPUTATION.R")
source("./06_SCENARIO_ALLOCATION_TABLES.R")
setwd("../rmd")

# General report: All CPCs
output_directory = "../outputs/scenarios/"
output_name      = paste0("IOTC-2024-TCAC13-INF0", i, "_Simulation_scenario_", i, "_results")
output_docx      = paste0(getwd(), "/", output_directory, output_name, ".docx")
output_pdf      = paste0(getwd(), "/", output_directory, output_name, ".pdf")

render("00_B_SIMULATIONS_ALL_CPCS.Rmd", 
       params = list(dynamictitle = paste0("TCAC simulation scenario ", i, " results")), 
       output_dir = output_directory, 
       output_file = output_docx)

wordApp = COMCreate("Word.Application") #creates COM object
wordApp[["Documents"]]$Open(Filename = output_docx) #opens your docx in wordApp
wordApp[["ActiveDocument"]]$SaveAs(output_pdf, FileFormat = 17) #saves as PDF 
wordApp[["ActiveDocument"]]$Close(SaveChanges = TRUE) #Closes the docx
wordApp$Quit() #quits the COM Word application
rm(list = "wordApp")

setwd("..")
}

# Generate ReadMe file



