# Source the scripts for loading and plotting the data
setwd("./initialisation/")
source("./00_CORE.R")
setwd("..")

# CONFIGURE ONE SCENARIO ####
BASELINE_WEIGHT      = 0.05 
COASTAL_STATE_WEIGHT = 0.05
CATCH_BASED_WEIGHT   = 1 - (BASELINE_WEIGHT + COASTAL_STATE_WEIGHT)

# COASTAL STATE COMPONENT (species-independent)
CS_EQUAL_WEIGHT          = 0.35
CS_SOCIO_ECONOMIC_WEIGHT = 0.475
  SE_HDI_WEIGHT = 0.3
  SE_GNI_WEIGHT = 0.3
  SE_SID_WEIGHT = 0.4
CS_NJA_WEIGHT            = 1 - (CS_EQUAL_WEIGHT + CS_SOCIO_ECONOMIC_WEIGHT) 
    
# CATCH-BASED COMPONENT
SPECIES_CODE_SELECTED           = "YFT"
SPECIES_SELECTED                = SPECIES_TABLE[SPECIES_CODE == SPECIES_CODE_SELECTED, SPECIES]
TARGET_TAC_T                    = 300000
HISTORICAL_CATCH_INTERVAL_START = 2000
HISTORICAL_CATCH_INTERVAL_END   = 2016
HISTORICAL_CATCH_AVERAGE        = period_average_catch_data    # or best_years_average_catch_data
HISTORICAL_CATCH_METHOD         = ifelse(sum(nchar(deparse(HISTORICAL_CATCH_AVERAGE)))>200, "Best \"n\" years", "Selected period")
ALLOCATION_TRANSITION           = seq(0.1, 1, 0.1)               # vector of length 10 of increasing cumulative re-attribution of the NJA catch to the coastal states
CATCH_BASED_WEIGHT_NJA_ATTRIBUTION_YEAR_01 = ALLOCATION_TRANSITION[1]
CATCH_BASED_WEIGHT_NJA_ATTRIBUTION_YEAR_02 = ALLOCATION_TRANSITION[2]
CATCH_BASED_WEIGHT_NJA_ATTRIBUTION_YEAR_03 = ALLOCATION_TRANSITION[3]
CATCH_BASED_WEIGHT_NJA_ATTRIBUTION_YEAR_04 = ALLOCATION_TRANSITION[4]
CATCH_BASED_WEIGHT_NJA_ATTRIBUTION_YEAR_05 = ALLOCATION_TRANSITION[5]
CATCH_BASED_WEIGHT_NJA_ATTRIBUTION_YEAR_06 = ALLOCATION_TRANSITION[6]
CATCH_BASED_WEIGHT_NJA_ATTRIBUTION_YEAR_07 = ALLOCATION_TRANSITION[7]
CATCH_BASED_WEIGHT_NJA_ATTRIBUTION_YEAR_08 = ALLOCATION_TRANSITION[8]
CATCH_BASED_WEIGHT_NJA_ATTRIBUTION_YEAR_09 = ALLOCATION_TRANSITION[9]
CATCH_BASED_WEIGHT_NJA_ATTRIBUTION_YEAR_10 = ALLOCATION_TRANSITION[10]

# Source the R allocation scripts
setwd("./initialisation/")
source("./05_SCENARIO_ALLOCATION_COMPUTATION.R")
source("./06_SCENARIO_ALLOCATION_TABLES.R")
setwd("../rmd")

# General report: All CPCs
render("00_A_SINGLE_SIMULATION_ALL_CPCS.Rmd", 
       output_dir = "../outputs/scenarios/", 
       output_file = "TAC_SIMULATION_SCENARIO_ALL_CPCS_EXAMPLE.docx")






# # Individual report: By CP
# for (j in CPC_data[STATUS %in% c("CP", "OBS"), CODE]){
#   
#   REPORT_OUTPUT_NAME = "TAC_SIMULATION_SCENARIO_"
#   }





